_wandb:
    value:
        cli_version: 0.19.9
        m: []
        python_version: 3.8.20
        t:
            "1":
                - 1
                - 5
                - 37
                - 41
                - 51
                - 53
                - 55
                - 82
            "2":
                - 1
                - 5
                - 37
                - 41
                - 51
                - 53
                - 55
                - 82
            "3":
                - 1
                - 16
                - 23
                - 55
            "4": 3.8.20
            "5": 0.19.9
            "8":
                - 5
            "12": 0.19.9
            "13": linux-x86_64
batch_size:
    value: 96
encoder:
    value: pointnet2
learning_rate:
    value: 0.0003
n_epochs:
    value: 200
num_bins:
    value: 360
